//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Country()
        {
            this.Diplomats = new HashSet<Diplomat>();
        }
    
        public int Id { get; set; }
        public string CountryCode { get; set; }
        public string Name { get; set; }
        public string Capital { get; set; }
        public Nullable<int> Population { get; set; }
        public Nullable<double> AreaSqKm { get; set; }
        public Nullable<int> FirstLang { get; set; }
        public Nullable<int> SecondLang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diplomat> Diplomats { get; set; }
    }
}
