//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diplomat
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public Nullable<int> Language { get; set; }
        public Nullable<int> Country { get; set; }
    
        public virtual Country Country1 { get; set; }
        public virtual Language Language1 { get; set; }
    }
}
