//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Translator
    {
        public int Id { get; set; }
        public string Fullname { get; set; }
        public byte[] Photo { get; set; }
        public byte[] Ensign { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
    }
}
